server:
  port: 9002
spring:
  application:
    name: feign-consumer
eureka:
  client:
    service-url:
#      defaultZone: http://127.0.0.1:7001/eureka
      defaultZone: http://47.112.238.117:7001/eureka
