server:
  port: 9003
spring:
  application:
    name: Test-Hystrix
eureka:
  client:
    service-url:
      # eureka的注册地址
      defaultZone: http://127.0.0.1:7001/eureka

feign:
  hystrix:
    enabled: true



