spring:
  security:
    basic:
      enabled: true
    user:
      name: user
      password: pwd123456
server:
  port: 7001
eureka:
  instance:
#    hostname: 127.0.0.1  	#本机地址 比如 localhost 都可以
    #测试的ip地址
    hostname: 47.112.238.117

  client:
    # 是否从eureka上获取注册信息，false 表示不会
    fetch-registry: false
    # 这里设置false表示eureka自己不会注册在eureka自己本身上
    register-with-eureka: false
    service-url:
     # 注：这个格式就是在命名后一定要空一格才能生效
#      defaultZone: http://user:pwd123456@127.0.0.1:7001/eureka/
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
